### ISSUE TITLE
Add packages to winget

### ISSUE THREAD

**Issue by pomazanbohdan** [thebookisclosed/ViVe#43]
https://winget.run/

**Comment by TheBossMagnus** [comment]
Winget's feature of .zip install is only in beta and for a limited number of programs. 
They don't accept any .zip program for now

**Comment by eabase** [comment]
It should be staright forward to create a winget-pkg YAML and upload to that repo.

**Comment by thebookisclosed** [comment]
Unless things have changed recently, creating packages for WinGet would introduce the need to create some sort of ViVe installer bundle like @TheBossMagnus's reply hints at. (which I don't like the idea of) It's supposed to be a simple portable app with no extra setup steps.

**Comment by eabase** [comment]
You don't need any zip, you just need to either ensure the exe is compiled standalone with library dependencies already included, or using a normal exe packaging tool. Like I said, this should be trivial, but if you're too lazy to google, I can't be of any help.

**Comment by thebookisclosed** [comment]
Have you considered just linking what you have in mind instead of smartass
replies? I was looking at
https://learn.microsoft.com/en-us/windows/package-manager/package/manifest
and don't see anything obvious. Winget still seems to be pretty installer
centric, and there is no official installer ViVe.

**Comment by sitiom** [comment]
A PR is already underway:
- https://github.com/microsoft/winget-pkgs/pull/92418

There is an issue, however, related to symlinks. https://github.com/microsoft/winget-pkgs/pull/92418#issuecomment-1366863557:
> In a VM, it installed successfully, and ran with no arguments. But both the /query and /enable arguments gave the same error:
> 
> ```
> PS C:\> C:\Users\user\AppData\Local\Microsoft\WinGet\Links\vivetool.exe /query
> ViVeTool v0.3.2 - Windows feature configuration tool
> 
> 
> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Albacore.ViVe, Version=2022.6.27.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
>    at Albacore.ViVeTool.Program.ProcessArgs(String[] args)
>    at Albacore.ViVeTool.Program.Main(String[] args)
> ```
> 
> Is there a missing dependency?

https://github.com/microsoft/winget-pkgs/pull/92418#issuecomment-1367038987:
> I guess it is the `Albacore.ViVe.dll` file in the same directory. I manually copied the remaining files to the `Links` folder and it works fine now.

@thebookisclosed Can you fix it so that it would try to find the DLL in the actual directory rather than the symlink directory?

**Comment by thebookisclosed** [comment]
ViVeTool makes no changes to how the library gets located, I don't think there is anything to fix on my end.
The PR was made without any sort of approval from my side, the manifest is most likely not well formed to make ViVe work correctly.

**Comment by sitiom** [comment]
> ViVeTool makes no changes to how the library gets located, I don't think there is anything to fix on my end.
> The PR was made without any sort of approval from my side, the manifest is most likely not well formed to make ViVe work correctly.

No, it's most likely how Winget symlinks the executable that makes it the problem. The [Scoop manifest](https://scoop.sh/#/apps?q=%22vivetool%22&s=0&d=1&o=true)  works perfectly as it uses a shim. The manifest is not well formed, and there was no ill intention in making the PR. I wish you didn't ask it to get closed.

**Comment by sitiom** [comment]
Just a heads up, Winget now supports binaries with DLLs as of https://github.com/microsoft/winget-cli/releases/tag/v1.9.25180, so let's do it properly this time:

- ~https://github.com/microsoft/winget-pkgs/pull/196219~ https://github.com/microsoft/winget-pkgs/pull/196478

**Comment by davidldennison** [comment]
@sitiom man of the people!

**Comment by sudg6** [comment]
@pomazanbohdan @thebookisclosed 
This issue should be closed, as it looks solved.
Winget confirms the existence of ViveTool under the ID: `thebookisclosed.Vive`

**Comment by sitiom** [comment]
- https://github.com/thebookisclosed/ViVe/pull/142 needs to be merged so updates can be published
