### ISSUE TITLE
Unhandled exception if feature ID not specified correctly 

### ISSUE THREAD

**Issue by riverar** [thebookisclosed/ViVe#58]
## Summary
When silly users, like me, specify feature IDs via `/id 123456` instead of `/id:123456` per the documentation, an unhandled exception occurs. (I only call this out because this also triggers my JIT debugger and interrupts my workflows.)

## Version
ViVeTool v0.3.1

## Steps to reproduce

1. Issue command: `vivetool /enable /id 123456`
2. Observe exception

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Albacore.ViVeTool.ArgumentBlock.Initialize(String[] args, ArgumentBlockFlags flags)
   at Albacore.ViVeTool.Program.ProcessArgs(String[] args)
   at Albacore.ViVeTool.Program.Main(String[] args)
```

**Comment by riverar** [comment]
Checking if `value` is null for various options in ArgumentBlock.cs and falling through if not seems to be the simplest fix here. Doing so will result in this output:

```
ViVeTool v0.3.1 - Windows feature configuration tool

Unrecognized parameter: /id

Unrecognized parameter: 123

No features were specified
```

If you're okay with that @thebookisclosed, I can submit a simple PR.

**Comment by thebookisclosed** [comment]
I'll take a look later this week, already have one more small change I want to push. No need for a PR.

**Comment by thebookisclosed** [comment]
Fixed in v0.3.2 (56e0bb4925e09bfc38fb8250d145eaca2b5313da)

**Comment by riverar** [comment]
Thanks @thebookisclosed!
